address/urls.py
from django.urls import path
from address.views import *

urlpatterns = [
    path('city-county-json/', get_json_address_city_data, name="city-json"),
    path('city-county-json/<int:id>/', get_json_address_county_data, name='county-json'),
    path('county-neighbourhood-json/<int:id>/', get_json_address_neighbourhood_data, name='county-json'),
]

degerleme/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.generic import RedirectView
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expert_info.urls')),
    path('adres/', include('address.urls')),

    path('favicon.ico', RedirectView.as_view(url='/static/img/favicon.png')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

expert_info/models.py
from django.db import models
from address.models import *
from user_accounts.models import User


# Create your models here.

class RaporEkle(models.Model):
    ISINMA = (
        ('1', "MERKEZİ SİSTEM"),
        ('2', "KOMBİ"),
        ('3', "SOBA"),
        ('4', "YOK"),
        ('6', "DİĞER"),
    )

    ASANSOR = (
        ('1','VAR'),
        ('2','YOK'),
    )

    OTOPARK = (
        ('1', 'VAR'),
        ('2', 'YOK'),
    )

    GUVENLIK = (
        ('1', 'VAR'),
        ('2', 'YOK'),
    )

    YAPI_KALITE = (
        ('1', 'LÜKS'),
        ('2', 'İYİ'),
        ('3', 'ORTA'),
        ('4', 'DÜŞÜK'),
        ('5', 'YAPI YOK'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=False)
    rapor_no = models.CharField(max_length=255, verbose_name="Rapor Numarası", null=True, blank=False)
    il = models.ForeignKey(Citys, on_delete=models.CASCADE, verbose_name="İl")
    ilce = models.ForeignKey(County, on_delete=models.CASCADE, verbose_name="İlçe")
    mahalle = models.ForeignKey(Neighbourhood, on_delete=models.CASCADE, verbose_name="Mahalle")
    ada = models.BigIntegerField(verbose_name="Ada", null=True, blank=False)
    parsel = models.BigIntegerField(verbose_name="Parsel", null=True, blank=False)
    enlem = models.FloatField(verbose_name="Enlem", null=True, blank=False)
    boylam = models.FloatField(verbose_name="Boylam", null=True, blank=False)
    ana_tasinmaz_nitelik = models.CharField(max_length=500, verbose_name="Ana Taşınmaz Nitelik", null=True, blank=False)
    nitelik = models.CharField(max_length=500, verbose_name="Nitelik", null=True, blank=False)
    yuzolcum = models.FloatField(verbose_name="Yüzölçüm", null=True, blank=False)
    deger = models.FloatField(verbose_name="Değer", null=True, blank=False)
    kat = models.CharField(verbose_name="Kat", max_length=255, null=True, blank=True)
    oda_sayisi = models.CharField(verbose_name="Oda Sayısı", max_length=255, null=True, blank=True)
    isinma_sistemi = models.CharField(choices=ISINMA, max_length=255, verbose_name="Isınma Sistemi", null=True, blank=False)
    deger_tarihi = models.DateField(verbose_name="Değerleme Tarihi", null=True, blank=False)
    asansor = models.CharField(choices=ASANSOR, max_length=255, null=True, blank=False, verbose_name="Asansör")
    otopark = models.CharField(choices=OTOPARK, max_length=255,null=True, blank=False, verbose_name="Otopark")
    guvenlik = models.CharField(choices=GUVENLIK, max_length=255, null=True, blank=False, verbose_name="Güvenlik")
    yapi_kalitesi = models.CharField(choices=YAPI_KALITE, max_length=255, null=True, blank=False, verbose_name="Yapı Kalitesi")
    yapim_yili = models.PositiveBigIntegerField(verbose_name="Yapım Yılı", null=True, blank=True)
    dosya_konumu = models.CharField(max_length=500, verbose_name="Dosya Konumu", null=True, blank=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    is_exist = models.BooleanField(default=True, null=True, verbose_name="Mevcut mu?")

    class Meta:
        verbose_name = "Eklenen Raporlar"
        verbose_name_plural = "Eklenen Raporlar"

    def __str__(self):
        return f"{self.rapor_no}"


class Maas(models.Model):
    YIL = (
        ('2023', '2023'),
        ('2024', '2024'),
        ('2025', '2025'),
        ('2026', '2026'),
        ('2027', '2027'),
        ('2028', '2028'),
        ('2029', '2029'),
        ('2030', '2030'),
        ('2031', '2031'),
        ('2032', '2032'),
        ('2033', '2033'),
        ('2034', '2034'),
    )

    AY = (
        ('1','Ocak'),
        ('2','Şubat'),
        ('3','Mart'),
        ('4','Nisan'),
        ('5','Mayıs'),
        ('6','Haziran'),
        ('7','Temmuz'),
        ('8','Ağustos'),
        ('9','Eylül'),
        ('10','Ekim'),
        ('11','Kasım'),
        ('12','Aralık'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=False)
    yil = models.CharField(choices=YIL, max_length=50, verbose_name="Yıl", null=True, blank=False)
    ay = models.CharField(choices=AY, max_length=50, verbose_name="Ay", null=True, blank=False)
    maas = models.FloatField(verbose_name="Maaş", null=True, blank=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    is_exist = models.BooleanField(default=True, null=True, verbose_name="Mevcut mu?")

    class Meta:
        verbose_name = "Maaşlar"
        verbose_name_plural = "Maaşlar"

    def __str__(self):
        return f"{self.user}"


class AracKira(models.Model):
    YIL = (
        ('2023', '2023'),
        ('2024', '2024'),
        ('2025', '2025'),
        ('2026', '2026'),
        ('2027', '2027'),
        ('2028', '2028'),
        ('2029', '2029'),
        ('2030', '2030'),
        ('2031', '2031'),
        ('2032', '2032'),
        ('2033', '2033'),
        ('2034', '2034'),
    )

    AY = (
        ('1','Ocak'),
        ('2','Şubat'),
        ('3','Mart'),
        ('4','Nisan'),
        ('5','Mayıs'),
        ('6','Haziran'),
        ('7','Temmuz'),
        ('8','Ağustos'),
        ('9','Eylül'),
        ('10','Ekim'),
        ('11','Kasım'),
        ('12','Aralık'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=False)
    yil = models.CharField(choices=YIL, max_length=50, verbose_name="Yıl", null=True, blank=False)
    ay = models.CharField(choices=AY, max_length=50, verbose_name="Ay", null=True, blank=False)
    kira = models.FloatField(verbose_name="Araç Kirası", null=True, blank=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    is_exist = models.BooleanField(default=True, null=True, verbose_name="Mevcut mu?")

    class Meta:
        verbose_name = "Araç Kiraları"
        verbose_name_plural = "Araç Kiraları"

    def __str__(self):
        return f"{self.user}"

class Prim(models.Model):

    YIL = (
        ('2023', '2023'),
        ('2024', '2024'),
        ('2025', '2025'),
        ('2026', '2026'),
        ('2027', '2027'),
        ('2028', '2028'),
        ('2029', '2029'),
        ('2030', '2030'),
        ('2031', '2031'),
        ('2032', '2032'),
        ('2033', '2033'),
        ('2034', '2034'),
    )

    AY = (
        ('1','Ocak'),
        ('2','Şubat'),
        ('3','Mart'),
        ('4','Nisan'),
        ('5','Mayıs'),
        ('6','Haziran'),
        ('7','Temmuz'),
        ('8','Ağustos'),
        ('9','Eylül'),
        ('10','Ekim'),
        ('11','Kasım'),
        ('12','Aralık'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=False)
    rapor_no = models.CharField(max_length=500, null=True, blank=True, verbose_name="Rapor Numarası")
    yil = models.CharField(choices=YIL, max_length=50, verbose_name="Yıl", null=True, blank=False)
    ay = models.CharField(choices=AY, max_length=50, verbose_name="Ay", null=True, blank=False)
    prim = models.FloatField(verbose_name="Rapor Ücreti", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    is_exist = models.BooleanField(default=True, null=True, verbose_name="Mevcut mu?")

    class Meta:
        verbose_name = "Primler"
        verbose_name_plural = "Primler"

    def __str__(self):
        return f"{self.user}"


class YapiMaliyetleri(models.Model):
    yapi_sinifi = models.CharField(max_length=10, verbose_name="Yapı Sınıfı", null=True, blank=False)
    birim_maliyet = models.FloatField(verbose_name="Birim Maliyet", null=True, blank=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    is_exist = models.BooleanField(default=True, null=True, verbose_name="Mevcut mu?")

    class Meta:
        verbose_name = "Yapı Birim Maliyetleri"
        verbose_name_plural = "Yapı Birim Maliyetleri"

    def __str__(self):
        return f"{self.yapi_sinifi}"

class ImarPlanOnaylari(models.Model):
    il = models.ForeignKey(Citys, on_delete=models.CASCADE, verbose_name="İl")
    ilce = models.ForeignKey(County, on_delete=models.CASCADE, verbose_name="İlçe")
    mahalle = models.ForeignKey(Neighbourhood, on_delete=models.CASCADE, verbose_name="Mahalle")
    ada = models.BigIntegerField(verbose_name="Ada", null=True, blank=False)
    parsel = models.BigIntegerField(verbose_name="Parsel", null=True, blank=False)
    tarih = models.DateField(verbose_name="Onay Tarihi", null=True, blank=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    is_exist = models.BooleanField(default=True, null=True, verbose_name="Mevcut mu?")

    class Meta:
        verbose_name = "İmar Planı Onay Tarihleri"
        verbose_name_plural = "İmar Planı Onay Tarihleri"

templates/pages/car_rental.html
{% extends 'layout.html' %}
{% load static %}
<title>{% block title %}Maaşlar{% endblock %}</title>
{% block car_rent %}

    <script src="{% static "plugins/jquery/jquery.min.js" %}"></script>
    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Araç Kiraları</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{% url 'mainpage' %}">Anasayfa</a></li>
                            <li class="breadcrumb-item">Araç Kiraları</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <div class="content">
            <div class="row p-0 m-0">
                <div class="col-lg-6">
                    <form action="" method="post" class="pt-2"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card">
                            <div class="card-body">
                                {{ form.as_p }}

                                {% if form.errors %}
                                    <div class="alert alert-danger" role="alert">
                                        {% for field, errors in form.errors.items %}
                                            {% for error in errors %}
                                                <b>{{ field }}</b>: {{ error }}
                                            {% endfor %}
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <input type="submit" class="btn btn-primary" name="rent_add" value="Ekle">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-6">
                    <div class="all-classes pt-2">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Tüm Araç Kiraları</h3>
                                <div class="card-tools">
                                    <div class="input-group input-group-sm" style="width: 150px;">
                                        <input type="text" name="table_search" onkeyup="searchFunction();" id="search"
                                               class="form-control float-right"
                                               placeholder="Search">

                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-default">
                                                <i class="fas fa-search"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body table-responsive p-0" style="height: 300px;">
                                <table class="table table-head-fixed text-nowrap" id="courseTable">
                                    <thead>
                                    <tr id="check-th">
                                        <th>Yıl</th>
                                        <th>Ay</th>
                                        <th>Araç Kirası</th>
                                        <th>Oluşturulma Tarihi</th>
                                        <th>Güncelleme Tarihi</th>
                                        <th>Durum</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for s in rent %}
                                        <tr>
                                            <td>{{ s.get_yil_display }}</td>
                                            <td>{{ s.get_ay_display }}</td>
                                            <td>{{ s.kira }}</td>
                                            <td>{{ s.created_at }}</td>
                                            <td>{{ s.updated_at }}</td>
                                            <td>

                                                <button type="button" class="btn btn-default bg-danger"
                                                        data-toggle="modal"
                                                        data-target="#modal-delete-{{ s.id }}">
                                                    Sil
                                                </button>
                                                <a href="{% url 'update_arac_kirasi' s.id %}" type="button"
                                                   class="btn btn-default bg-info">
                                                    Güncelle
                                                </a>

                                                <div class="modal fade" id="modal-delete-{{ s.id }}">
                                                    <div class="modal-dialog">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h4 class="modal-title">Silmek istediğinize emin
                                                                    misiniz?</h4>
                                                                <button type="button" class="close" data-dismiss="modal"
                                                                        aria-label="Close">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">
                                                                <h5 class="text-bold">Silinecek araç kirası:</h5>
                                                                <p>Yıl: {{ s.get_yil_display }}</p>
                                                                <p>Ay: {{ s.get_ay_display }}</p>
                                                                <p>Maaş: {{ s.kira }} TL</p>
                                                            </div>
                                                            <div class="modal-footer justify-content-between">
                                                                <button type="button" class="btn btn-default"
                                                                        data-dismiss="modal">
                                                                    Kapat
                                                                </button>
                                                                <a href="{% url 'delete_arac_kirasi' s.id %}"
                                                                   class="btn btn-danger">Sil</a>
                                                            </div>
                                                        </div>
                                                        <!-- /.modal-content -->
                                                    </div>
                                                    <!-- /.modal-dialog -->
                                                </div>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                                <span id="no-data"></span>
                            </div>
                            <!-- /.card-body -->
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="{% static 'js/admin/course.js' %}"></script>
    <script src="{% static "plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

    <script src="{% static 'js/admin/get_categories.js' %}"></script>

    <script>
        function searchFunction() {
            let input, filter, table, tr, td, j;
            input = document.getElementById("search");
            filter = input.value.toLowerCase();
            table = document.getElementById("courseTable");
            tr = table.getElementsByTagName("tr");

            for (j = 0; j < tr.length; j++) {
                td = tr[j].getElementsByTagName("td");
                msg = document.getElementById("no-data");

                if (td.length > 0) {
                    if (td[0].innerHTML.toLocaleLowerCase().indexOf(filter) > -1 ||
                        td[1].innerHTML.toLocaleLowerCase().indexOf(filter) > -1 ||
                        td[2].innerHTML.toLocaleLowerCase().indexOf(filter) > -1 ||
                        td[3].innerHTML.toLocaleLowerCase().indexOf(filter) > -1 ||
                        td[4].innerHTML.toLocaleLowerCase().indexOf(filter) > -1 ||
                        td[5].innerHTML.toLocaleLowerCase().indexOf(filter) > -1) {
                        tr[j].style.display = ""
                        msg.innerHTML = ""
                    } else {
                        tr[j].style.display = "none"
                    }
                }

                if (td.length == 0) {
                    msg.innerHTML = "Aramanızla eşleşen kayıt bulunamadı."
                }

            }
        }
    </script>

{% endblock %}

templates/pages/near_reports.html
{% extends 'layout.html' %}
{% load static %}
<title>{% block title %}Yakın Rapor{% endblock %}</title>
{% block near_rapor %}

    <script src="{% static "plugins/jquery/jquery.min.js" %}"></script>
    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Yakn Rapor</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{% url 'mainpage' %}">Anasayfa</a></li>
                            <li class="breadcrumb-item">Yakın Rapor</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <div class="content">
            <div class="row p-0 m-0">
                <div class="col-lg-6">
                    <form action="" method="post" class="pt-2"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="id_enlem">Enlem</label>
                                    <input type="number" name="enlem" step="any" class="form-control"
                                           required="" id="id_enlem">
                                </div>
                                <div class="form-group">
                                    <label for="id_boylam">Boylam</label>
                                    <input type="number" name="boylam" step="any" class="form-control"
                                           required="" id="id_boylam">
                                </div>
                                <div class="form-group">
                                    <label for="id_mesafe">Mesafe</label>
                                    <input type="number" name="mesafe" step="any" class="form-control"
                                           required="" id="id_mesafe">
                                </div>
                            </div>

                            <div class="card-footer">
                                <input type="submit" class="btn btn-primary" name="query" value="Sorgula">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-6">
                    <div class="all-classes pt-2">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Tüm Yakın Raporlar</h3>
                                <div class="card-tools">
                                    <div class="input-group input-group-sm" style="width: 150px;">
                                        <input type="text" name="table_search" onkeyup="searchFunction();" id="search"
                                               class="form-control float-right"
                                               placeholder="Search">

                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-default">
                                                <i class="fas fa-search"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body table-responsive p-0" style="height: 300px;">
                                <table class="table table-head-fixed text-nowrap" id="courseTable">
                                    <thead>
                                    <tr id="check-th">
                                        <th>Rapor Numarası</th>
                                        <th>İl</th>
                                        <th>İlçe</th>
                                        <th>Mahalle</th>
                                        <th>Ada</th>
                                        <th>Parsel</th>
                                        <th>Enlem</th>
                                        <th>Boylam</th>
                                        <th>Ana Taşınmaz Nitelik</th>
                                        <th>Nitelik</th>
                                        <th>Yüzölçüm</th>
                                        <th>Değer</th>
                                        <th>Kat</th>
                                        <th>Oda Sayısı</th>
                                        <th>Isınma Sistemi</th>
                                        <th>Değer Tarihi</th>
                                        <th>Asansör</th>
                                        <th>Otopark</th>
                                        <th>Güvenlik</th>
                                        <th>Yapı Kalitesi</th>
                                        <th>Yapım Yılı</th>
                                        <th>Dosya Konumu</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for qr in query_reports %}
                                        <tr>
                                            <td>{{ qr.rapor_no }}</td>
                                            <td>{{ qr.il }}</td>
                                            <td>{{ qr.ilce }}</td>
                                            <td>{{ qr.mahalle }}</td>
                                            <td>{{ qr.ada }}</td>
                                            <td>{{ qr.parsel }}</td>
                                            <td>{{ qr.enlem }}</td>
                                            <td>{{ qr.boylam }}</td>
                                            <td>{{ qr.ana_tasinmaz_nitelik }}</td>
                                            <td>{{ qr.nitelik }}</td>
                                            <td>{{ qr.yuzolcum }}</td>
                                            <td>{{ qr.deger }}</td>
                                            <td>{{ qr.kat }}</td>
                                            <td>{{ qr.oda_sayisi }}</td>
                                            <td>{{ qr.get_isinma_sistemi_display }}</td>
                                            <td>{{ qr.deger_tarihi }}</td>
                                            <td>{{ qr.get_asansor_display }}</td>
                                            <td>{{ qr.get_otopark_display }}</td>
                                            <td>{{ qr.get_guvenlik_display }}</td>
                                            <td>{{ qr.get_yapi_kalitesi_display }}</td>
                                            <td>{{ qr.yapim_yili }}</td>
                                            <td>{{ qr.dosya_konumu }}</td>
                                            <td>
                                                <a href="{% url 'show_rapor' qr.id %}"
                                                   class="btn btn-sm btn-primary">Görüntüle</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                                <span id="no-data"></span>
                            </div>
                            <!-- /.card-body -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="row d-flex justify-content-center align-items-center">
                <div class="col-lg-6">
                    <div class="card">
                    <div class="card-body">
                        {{ map|safe }}
                    </div>
                </div>
                </div>
            </div>
        </div>


    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="{% static 'js/admin/course.js' %}"></script>
    <script src="{% static "plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

    <script src="{% static 'js/admin/get_categories.js' %}"></script>

    <script>
        function searchFunction() {
            let input, filter, table, tr, td, j;
            input = document.getElementById("search");
            filter = input.value.toLowerCase();
            table = document.getElementById("courseTable");
            tr = table.getElementsByTagName("tr");

            for (j = 0; j < tr.length; j++) {
                td = tr[j].getElementsByTagName("td");
                msg = document.getElementById("no-data");

                if (td.length > 0) {
                    if (td[0].innerHTML.toLocaleLowerCase().indexOf(filter) > -1 ||
                        td[1].innerHTML.toLocaleLowerCase().indexOf(filter) > -1 ||
                        td[2].innerHTML.toLocaleLowerCase().indexOf(filter) > -1 ||
                        td[3].innerHTML.toLocaleLowerCase().indexOf(filter) > -1 ||
                        td[4].innerHTML.toLocaleLowerCase().indexOf(filter) > -1 ||
                        td[5].innerHTML.toLocaleLowerCase().indexOf(filter) > -1) {
                        tr[j].style.display = ""
                        msg.innerHTML = ""
                    } else {
                        tr[j].style.display = "none"
                    }
                }

                if (td.length == 0) {
                    msg.innerHTML = "Aramanızla eşleşen kayıt bulunamadı."
                }

            }
        }
    </script>

{% endblock %}